services:
  # ============================================================================
  # PASO 1: Pipeline DVC (ingesta de datos + preparación + entrenamiento)
  # ============================================================================
  dvc-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-housing-dvc-pipeline
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=mlruns
      - MLFLOW_EXPERIMENT_NAME=housing-price-prediction
      - MODEL_PATH=models/production
      - DATA_PATH=data/housing.csv
      - RAW_DATA_PATH=data/raw
      - KAGGLE_USERNAME=${KAGGLE_USERNAME:-marestrepohi}
      - KAGGLE_KEY=${KAGGLE_KEY:-037c85291a66a2b8159a83970e814353}
      - ENABLE_MONITORING=true
      - LOG_LEVEL=INFO
    command: >
      sh -c "
        echo '🔧 Paso 1: Inicializando repositorio DVC (sin SCM)...' &&
        dvc init --no-scm --force &&
        echo '✅ DVC inicializado' &&
        echo '🔄 Paso 2: Ejecutando pipeline DVC (ingesta + preparación + entrenamiento)...' &&
        dvc repro &&
        echo '✅ Pipeline DVC completado' &&
        echo '🤖 Paso 3: Modelos entrenados y mejor modelo seleccionado' &&
        echo '✅ Pipeline finalizado - datos, modelos, mlruns generados' &&
        echo '👉 Siguiente: MLflow UI se iniciará en puerto 5000' &&
        echo '🎯 El contenedor DVC saldrá ahora - ¡esto es esperado!'
      "
    restart: "no"
    networks:
      - mlops-housing-network

  # ============================================================================
  # PASO 2: MLflow UI (después del pipeline DVC)
  # ============================================================================
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-housing-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns:ro
    command: >
      sh -c "
        echo '⏳ Esperando a que el pipeline DVC se complete...' &&
        while [ ! -d /app/mlruns ] || [ -z \"$$(ls -A /app/mlruns 2>/dev/null)\" ]; do
          echo '   Esperando directorio mlruns...' &&
          sleep 5
        done &&
        echo '✅ Directorio mlruns encontrado' &&
        echo '📊 Paso 4: Iniciando MLflow UI en puerto 5000...' &&
        echo '   Usando mlruns desde: /app/mlruns' &&
        mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:///app/mlruns
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      dvc-pipeline:
        condition: service_completed_successfully
    networks:
      - mlops-housing-network

  # ============================================================================
  # PASO 3: FastAPI (después de MLflow)
  # ============================================================================
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-housing-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models:ro
      - ./mlruns:/app/mlruns:ro
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - MODEL_PATH=models/production
      - ENABLE_MONITORING=true
      - LOG_LEVEL=INFO
    command: >
      sh -c "
        echo '⏳ Esperando a que MLflow UI esté listo...' &&
        sleep 10 &&
        echo '🚀 Paso 5: Iniciando FastAPI en puerto 8000...' &&
        echo '   Modelo: models/production/latest/' &&
        uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - mlops-housing-network

  # ============================================================================
  # PASO 4: Frontend (después de API)
  # ============================================================================
  frontend:
    image: node:20-alpine
    container_name: mlops-housing-frontend
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app
      - ./data:/app/public/data:ro
      - ./mlruns:/app/public/mlruns:ro
      - ./models:/app/public/models:ro
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_MLFLOW_URL=http://localhost:5000
    command: >
      sh -c "
        echo '⏳ Esperando a que API esté lista...' &&
        sleep 10 &&
        echo '📦 Paso 6: Instalando dependencias del frontend...' &&
        npm install &&
        echo '🔄 Paso 7: Sincronizando carpetas (data, mlruns, modelos)...' &&
        echo '   ✅ data/ -> public/data/ (montado)' &&
        echo '   ✅ mlruns/ -> public/mlruns/ (montado)' &&
        echo '   ✅ models/ -> public/models/ (montado)' &&
        echo '🌐 Paso 8: Iniciando servidor Vite en puerto 8080...' &&
        echo '   Frontend consumirá:' &&
        echo '   - API: http://localhost:8000' &&
        echo '   - MLflow: http://localhost:5000' &&
        npm run dev -- --host 0.0.0.0 --port 8080
      "
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
      mlflow:
        condition: service_healthy
    networks:
      - mlops-housing-network

networks:
  mlops-housing-network:
    driver: bridge
